### ISSUE TITLE
Failed to import certain records (already exist or are missing fields?)

### ISSUE THREAD

**Issue by Braunson** [turbo124/Plane2Ninja#4]
I'm not sure if this is related to the recent quotes code push but when trying to import I receive this error.. `Undefined index: account_email_settings`

When Importing the Data and Settings checkboxes were checked. Looking at the exported json, there's no `settings` or `account_email_settings` arrays.

**NOTE:**  This is on a fresh install of the latest InvoiceNinja.

---

# Issue 1 - Errors importing data only

Now that I think about it, settings wouldn't really be the same and you don't even back them up, duh. I however did try to re-import again and received this error with just the data checked:

```
Successfully created 33 client(s)
Successfully created 81 invoice(s)
Successfully created 64 payment(s)
Successfully created 4 quotes(s)
Successfully created 7 product(s)
The following records failed to import, they either already exist or are missing required fields.
{"invoice_id":6}
{"invoice_id":30}
{"invoice_id":42}
{"invoice_id":43}
{"invoice_id":44}
{"invoice_id":45}
{"invoice_id":46}
{"invoice_id":47}
{"invoice_id":49}
{"invoice_id":50}
{"invoice_id":51}
{"invoice_id":52}
{"invoice_id":53}
{"invoice_id":54}
{"invoice_id":55}
{"invoice_id":56}
{"invoice_id":61}
{"invoice_id":63}
{"invoice_id":82}
{"invoice_id":83}
{"invoice_id":84}
{"invoice_id":85}
```

---

# Issue 2 - Client/invoice balance is negative

Another note: when viewing the clients, the balance shows negative numbers i.e. `$-620.00` for a client who's already paid up? This is what's show in the activity area after I create the client.. see https://goo.gl/e43i2Z

I click the invoices tab and it shows the invoice, the amount of 620 then balance equals 0 and status is paid. The payments tab shows the +620 payment. So why would this customer's balance be -$620? Is this perhaps an InvoiceNinja bug instead?

---

# Issue 3 - Invoice due date not moved over

It seems the due date is not moved over for the invoice

---

# Issue 4 - Client Portal does not show invoices or payments?

Perhaps we're getting into an InvoiceNinja bug here but shouldn't all invoices paid or unpaid show in the client's web portal? The same goes for the payments area on the web portal? The dashboard shows  $620 paid to date and an open balance of $-620 for the same client with the negative issue above.

**Comment by Braunson** [comment]
Update on issue # 2, looking at the json file in the array of the same invoice as I'm talking about above.. shows on the invoice array under "paid" is 620, then farther down under "payments" shows another payment for $620. Would this be causing the negative issue (because of a double payment?)

I've removed any confidential info..
```
{
	"client_id": 20,
	"invoice_number": "20141038",
	"paid": "620.00",
	"po_number": "",
	"terms": "...",
	"public_notes": "",
	"invoice_date": "2014-10-12",
	"due_date": null,
	"invoice_status_id": 1,
	"is_amount_discount": null,
	"discount": 0,
	"tax_name1": "",
	"tax_rate1": 0,
	"tax_name2": "",
	"tax_rate2": 0,
	"invoice_design_id": 1,
	"invoice_items": [
		....
	],
	"payments": [
		{
			"id": 37,
			"amount": 620,
			"payment_date": "2014-12-31",
			"client_id": 20,
			"invoice_id": 38,
			"payment_type_id": 3
		}
	]
}
]
```

**Comment by turbo124** [comment]
The issue is the invoice_status_id is not being transformed correctly.

I'll have a look at this.

**Comment by Braunson** [comment]
After looking at the statuses...

| Status   	| InvoicePlane             	| InvoiceNinja 	|
|----------	|--------------------------	|--------------	|
| Draft    	| 1                        	| 1            	|
| Sent     	| 2                        	| 2            	|
| Viewed   	| 3                        	| 3            	|
| Paid     	| 4                        	| 6            	|
| Approved 	| Not Supported            	| 4            	|
| Partial  	| Not Supported            	| 5            	|
| Overdue  	| Bool column `is_overdue` 	| -1           	|
| Unpaid   	| Not Supported            	| -2           	|

From https://github.com/turbo124/Plane2Ninja/blob/6eaa5df42cfe320f47110a9324da6bce3d65b280/app/Plane2Ninja/Transformers/InvoiceTransformer.php#L102 and https://github.com/InvoicePlane/InvoicePlane/blob/3cd04a62bff7e7b8727b9aef2f5b5939d775ab34/application/modules/invoices/models/Mdl_invoices.php#L451

**Comment by turbo124** [comment]
@Braunson thanks, 
https://github.com/turbo124/Plane2Ninja/commit/99586c4a670536ab2108d7e82b27b3122a7bb027

Should fix this.

**Comment by Braunson** [comment]
Thanks @turbo124 

I'm still getting the `records failed to import` error, same set of data on a fresh install, different invoice_ids errors.

```
Successfully created 33 client(s)
Successfully created 81 invoice(s)
Successfully created 64 payment(s)
Successfully created 4 quotes(s)
Successfully created 7 product(s)
The following records failed to import, they either already exist or are missing required fields.
{"invoice_id":30}
{"invoice_id":42}
{"invoice_id":43}
{"invoice_id":44}
{"invoice_id":45}
{"invoice_id":46}
{"invoice_id":47}
{"invoice_id":49}
{"invoice_id":50}
{"invoice_id":51}
{"invoice_id":52}
{"invoice_id":53}
{"invoice_id":54}
{"invoice_id":55}
{"invoice_id":56}
{"invoice_id":61}
{"invoice_id":63}
{"invoice_id":85}
```

The balance is still negatives and the payment status is wonky, I have say 5 invoices all previously paid in full, now some say paid, others draft.

**Comment by turbo124** [comment]
There must be another status for the invoices that we are not picking up. the system will default to 1 (draft) if it can't match the status.

**Comment by Braunson** [comment]
It's weird as I don't have an invoice 30 for example in the database or the export json. I do have a client with the id of 30 and a payment with the id of 30.

I think the invoice status discrepancy is caused by marking some invoices as 'paid' without entering a payment resulting it to show a balance and be marked as a draft, and the one's with an attached payment are marked as paid.  Case solved with that one.

Still not sure about the records failure and the negative numbers?

**Comment by turbo124** [comment]
I think the ids are referring to the invoices being created on the invoice ninja side.

I'll have a chat with hillel @ IN to see what he suggests. I am sure the issue revolves around the invoice_status

**Comment by Braunson** [comment]
Ok, we'll see what he says.. Also I noticed from the exporter, under the invoice payments you have the column `"invoice_id"` but the invoice itself doesn't have an ID set?

**Comment by turbo124** [comment]
@Braunson are you able to send a sample json file to me please? I think that is the only way we can figure out what is going on with your dataset to see this issue. Please send to turbo124@gmail.com if you are able to anonymize the data.

**Comment by Braunson** [comment]
@turbo124 Working on it, a ton of data to go through, once I'm done I'll send it over

**Comment by turbo124** [comment]
https://github.com/turbo124/Plane2Ninja/commit/ad490ac83ba3e8e581ee5b6f407a13801b087e5b resolves this.

**Comment by Braunson** [comment]
Re-ran the import and received..

```
Successfully created 33 client(s)
Successfully created 81 invoice(s)
Successfully created 64 payment(s)
Successfully created 4 quotes(s)
Successfully created 7 product(s)
The following records failed to import, they either already exist or are missing required fields.
{"invoice_id":30}
{"invoice_id":42}
{"invoice_id":43}
{"invoice_id":44}
{"invoice_id":45}
{"invoice_id":46}
{"invoice_id":47}
{"invoice_id":49}
{"invoice_id":50}
{"invoice_id":51}
{"invoice_id":52}
{"invoice_id":53}
{"invoice_id":54}
{"invoice_id":55}
{"invoice_id":56}
{"invoice_id":61}
{"invoice_id":63}
{"invoice_id":85}
```

**Comment by turbo124** [comment]
@Braunson this may be a false positive.

Are there any records missing?

**Comment by Braunson** [comment]
I did some more digging and expanded the import to include the validator error. It seems all invoices and quotes were imported. 

This is my updated loop for invoice payments in `ImportService.php` line 222-235

```
foreach ($jsonInvoice['payments'] as $jsonPayment) {
    $jsonPayment['invoice_id'] = $invoice->public_id;
    $pvalidate = EntityModel::validate($jsonPayment, ENTITY_PAYMENT);
    if ($pvalidate === true) {
        $jsonPayment['client_id'] = $client->id;
        $jsonPayment['invoice_id'] = $invoice->id;
        $payment = $this->paymentRepo->save($jsonPayment);
        $this->addSuccess($payment);
    } else {
        $jsonPayment['error'] = $pvalidate; // THIS RIGHT HERE
        $this->addFailure(ENTITY_PAYMENT, $jsonPayment);
        continue;
    }
}
```

** Output:** 

```
{"invoice_id":30,"error":"The amount field is required."}
{"invoice_id":42,"error":"The amount field is required."}
{"invoice_id":43,"error":"The amount field is required."}
{"invoice_id":44,"error":"The amount field is required."}
{"invoice_id":45,"error":"The amount field is required."}
{"invoice_id":46,"error":"The amount field is required."}
{"invoice_id":47,"error":"The amount field is required."}
{"invoice_id":49,"error":"The amount field is required."}
{"invoice_id":50,"error":"The amount field is required."}
{"invoice_id":51,"error":"The amount field is required."}
{"invoice_id":52,"error":"The amount field is required."}
{"invoice_id":53,"error":"The amount field is required."}
{"invoice_id":54,"error":"The amount field is required."}
{"invoice_id":55,"error":"The amount field is required."}
{"invoice_id":56,"error":"The amount field is required."}
{"invoice_id":61,"error":"The amount field is required."}
{"invoice_id":63,"error":"The amount field is required."}
{"invoice_id":85,"error":"The amount field is required."}
```

Looking at the `CreatePaymentAPIRequest.php` file, the `amount` rules are `required|numeric|not_in:0`.

I'm going to assume that this is due to there being no payment(s) on those invoices (they were marked as paid in the previous system but had no recorded payments). So I guess we're all good now. Thank you very much @turbo124 for your help on this, it's greatly appreciated!
